---
- name: Install NRPE on worker node
  hosts: worker
  become: yes

  tasks:
    - name: Install NRPE and Nagios plugins
      apt:
        name:
          - nagios-nrpe-server
          - nagios-plugins
        state: present
        update_cache: yes

    - name: Allow master in NRPE config (localhost)
      lineinfile:
        path: /etc/nagios/nrpe.cfg
        regexp: '^allowed_hosts='
        line: "allowed_hosts=127.0.0.1,{{ ansible_default_ipv4.address }}"

    - name: Restart NRPE service
      systemd:
        name: nagios-nrpe-server
        state: restarted
        enabled: yes

